import type { Metadata } from "next";
import "./globals.css";
import iranSans from "@/constant/iranSansFont";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: {
    template: "%s | بلاگ",
    default: "بلاگ اپ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={`${iranSans.variable}`}>{children}</body>
    </html>
  );
}
