import type { Metadata } from "next";
import "./globals.css";
import iranSans from "@/constant/iranSansFont";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={`${iranSans.variable}`}>
        <Header />
        <div> {children}</div>
      </body>
    </html>
  );
}
