import type { Metadata } from "next";
import "./globals.css";
import iranSans from "@/constant/iranSansFont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={`${iranSans.variable}`}>
        <div className=""></div>
        {children}
      </body>
    </html>
  );
}
